Add HalfNormal distribution
rlouf/mcx pull request #100
Opened 2021-03-16 15:34 UTC by shwinnn

Adds the HalfNormal distribution. I force it to be bounded below at 0 to match the APIs of other PPL libraries (e.g. [numpyro](https://numpyro.readthedocs.io/en/v0.2.0/distributions.html#halfnormal), [tensorflow probability](https://www.tensorflow.org/probability/api_docs/python/tfp/distributions/HalfNormal)

2021-03-16 16:07 UTC, rlouf requested changes
Thank you for taking the time to add this distribution! I added a few comments. Before merging I would need a few tests, which you can probably get from modifying the Normal distribution's test. And also a test that makes sure that values out of support return `-inf`. Thank you again.

2021-03-16 16:07 UTC, rlouf commented on mcx/distributions/halfnormal.py
> +    support = constraints.real
```suggestion
    support = constraints.positive
```

2021-03-30 14:55 UTC, rlouf commented
I would really like to merge this before the first release. Is there anything I can do to help?

2021-03-30 15:30 UTC, shwinnn commented
Hi, sorry I just haven't found the time to write the tests. If I have the downtime I will have a look but I don't have a specific timeframe for you I'm afraid!

2021-03-30 15:46 UTC, rlouf commented
No problem, take your time!

2021-04-12 06:14 UTC, rlouf commented
It looks good to me, merging. Thank you for taking the time to add the `HalfNormal` distribution to MCX!

2021-04-12 06:17 UTC, rlouf commented
Actually, would you mind squashing all your commits? Github doesn't suggest you as a co-author if I squash the commits myself here, and I wouldn't want you to not appear as a contributor.

2021-04-12 06:17 UTC, rlouf requested changes
Just squash your commits and we're good to go.

2021-04-12 12:52 UTC, rlouf commented
Merging, thanks again!

2021-04-12 12:53 UTC, merged